disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - empty_string

included:
  - Sources
  - Tests

excluded:
  - .build
  - Pods
  - DerivedData

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - to
    - db

reporter: "xcode"
