name: Lint

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          severity: warning

  shfmt:
    name: Shell Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          wget https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64 -O /usr/local/bin/shfmt
          chmod +x /usr/local/bin/shfmt

      - name: Run shfmt
        run: shfmt -d -i 2 .

  bats:
    name: Bats Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.10.0

      - name: Run bats tests
        run: |
          if [ -d "tests" ]; then
            bats tests/
          else
            echo "No tests directory found, skipping"
          fi
