name: Lint

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build and Test
        run: swift test --enable-code-coverage

      - name: Generate coverage report
        run: |
          xcrun llvm-cov export -format="lcov" \
            .build/debug/{{REPO_NAME}}PackageTests.xctest/Contents/MacOS/{{REPO_NAME}}PackageTests \
            -instr-profile .build/debug/codecov/default.profdata > coverage.lcov

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.lcov
